SELECT * FROM [TestDB].[dbo].Invoice_Details where Clientname='ABC'
SELECT * FROM [TestDB].[dbo].[Invoice_Summary] where Clientname='ABC'
SELECT * FROM [TestDB].[dbo].OrderDetails where Clientname='ABC'
SELECT * FROM [TestDB].[dbo].[ServiceContract] where Clientname='ABC'
SELECT * FROM [TestDB].[dbo].ServiceDetailMaster where Clientname='ABC'
